# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: texttype.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='texttype.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0etexttype.proto\"#\n\x0fTextTypeRequest\x12\x10\n\x08raw_text\x18\x01 \x01(\t\"+\n\x10TextTypeResponse\x12\x17\n\x04type\x18\x01 \x01(\x0e\x32\t.TextType*-\n\x08TextType\x12\x08\n\x04NEWS\x10\x00\x12\x0b\n\x07OPINION\x10\x01\x12\n\n\x06\x41\x44VICE\x10\x02\x32\x37\n\x05Types\x12.\n\x07GetType\x12\x10.TextTypeRequest\x1a\x11.TextTypeResponseb\x06proto3'
)

_TEXTTYPE = _descriptor.EnumDescriptor(
  name='TextType',
  full_name='TextType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEWS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPINION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADVICE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=100,
  serialized_end=145,
)
_sym_db.RegisterEnumDescriptor(_TEXTTYPE)

TextType = enum_type_wrapper.EnumTypeWrapper(_TEXTTYPE)
NEWS = 0
OPINION = 1
ADVICE = 2



_TEXTTYPEREQUEST = _descriptor.Descriptor(
  name='TextTypeRequest',
  full_name='TextTypeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_text', full_name='TextTypeRequest.raw_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=53,
)


_TEXTTYPERESPONSE = _descriptor.Descriptor(
  name='TextTypeResponse',
  full_name='TextTypeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='TextTypeResponse.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=98,
)

_TEXTTYPERESPONSE.fields_by_name['type'].enum_type = _TEXTTYPE
DESCRIPTOR.message_types_by_name['TextTypeRequest'] = _TEXTTYPEREQUEST
DESCRIPTOR.message_types_by_name['TextTypeResponse'] = _TEXTTYPERESPONSE
DESCRIPTOR.enum_types_by_name['TextType'] = _TEXTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextTypeRequest = _reflection.GeneratedProtocolMessageType('TextTypeRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEXTTYPEREQUEST,
  '__module__' : 'texttype_pb2'
  # @@protoc_insertion_point(class_scope:TextTypeRequest)
  })
_sym_db.RegisterMessage(TextTypeRequest)

TextTypeResponse = _reflection.GeneratedProtocolMessageType('TextTypeResponse', (_message.Message,), {
  'DESCRIPTOR' : _TEXTTYPERESPONSE,
  '__module__' : 'texttype_pb2'
  # @@protoc_insertion_point(class_scope:TextTypeResponse)
  })
_sym_db.RegisterMessage(TextTypeResponse)



_TYPES = _descriptor.ServiceDescriptor(
  name='Types',
  full_name='Types',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=147,
  serialized_end=202,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetType',
    full_name='Types.GetType',
    index=0,
    containing_service=None,
    input_type=_TEXTTYPEREQUEST,
    output_type=_TEXTTYPERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TYPES)

DESCRIPTOR.services_by_name['Types'] = _TYPES

# @@protoc_insertion_point(module_scope)
